-- Crear tabla AJENO_RAM
CREATE TABLE IF NOT EXISTS AJENOS.AJENO_RAM (
    ID_AJENO BIGINT NOT NULL,
    UNIDADES_EMPAQUETADO INTEGER NOT NULL DEFAULT 1,
    MULTIPLO_MINIMO INTEGER NOT NULL DEFAULT 1,
    ID_TIPO_ESTADO_AJENO_RAM SMALLINT NOT NULL DEFAULT 1,
    ID_UNIDADES_MEDIDA SMALLINT NOT NULL DEFAULT 1,
    IMAGE_REF VARCHAR(400) NULL,
    PRIMARY KEY (ID_AJENO)
);