-- Crear la tabla AJENO
CREATE TABLE IF NOT EXISTS AJENOS.AJENO (
    ID_AJENO BIGINT NOT NULL,
    NOMBRE VARCHAR(1500) NOT NULL,
    ID_TIPO_AJENO SMALLINT NOT NULL,
    DESCRIPCION VARCHAR(1500) NULL,
    ID_DEPARTAMENTO_EMPRESA_GRUPO SMALLINT NOT NULL,
    ID_MAQUINA_ESTADO_AJENOS INT NOT NULL,
    FECHA_ALTA TIMESTAMP NOT NULL,
    USUARIO_ALTA VARCHAR(40) NOT NULL,
    FECHA_MODIFICACION TIMESTAMP NULL,
    USUARIO_MODIFICACION VARCHAR(40) NULL,
    ID_UNIDADES_MEDIDA SMALLINT NULL,
    PRIMARY KEY (ID_AJENO)
);