CREATE TABLE IF NOT EXISTS AJENOS.ALIAS (
    ID_ALIAS INTEGER NOT NULL,
    ID_TIPO_ALIAS SMALLINT NOT NULL,
    ID_TIPO_ESTACIONALIDAD SMALLINT NOT NULL,
    ID_TIPO_ESTADO_ALIAS SMALLINT NOT NULL,
    FECHA_ALTA TIMESTAMP NOT NULL,
    USUARIO_ALTA VARCHAR(140) NOT NULL,
    FECHA_MODIFICACION TIMESTAMP NULL,
    USUARIO_MODIFICACION VARCHAR(140) NULL,
    FECHA_BAJA TIMESTAMP NULL,
    USUARIO_BAJA VARCHAR(140) NULL,
    ID_TIPO_CONEXION_ORIGEN_DATO_ALIAS SMALLINT NULL,
    ID_TIPO_ORIGEN_DATO_ALIAS SMALLINT NULL,
    INFORMACION_ORIGEN_DATO VARCHAR(1100) NULL,
    ENTRENADO DECIMAL(1,0) NOT NULL DEFAULT 0,
    PRIMARY KEY (ID_ALIAS)
);
