CREATE TABLE IF NOT EXISTS AJENOS.ALIAS_ACOPLE_TAREA (
    ID_TAREA_RAM BIGINT NOT NULL,
    ID_ALIAS INTEGER NOT NULL,
    ID_ALIAS_ACOPLE INTEGER NOT NULL,
    ID_TIPO_ORIGEN_DATO_ALIAS SMALLINT NULL,
    FECHA_ALTA TIMESTAMP NOT NULL,
    USUARIO_ALTA VARCHAR(140) NOT NULL,
    FECHA_MODIFICACION TIMESTAMP NULL,
    USUARIO_MODIFICACION VARCHAR(140) NULL,
    FECHA_BAJA TIMESTAMP NULL,
    USUARIO_BAJA VARCHAR(140) NULL,
    RATIO_ACOPLE INTEGER NULL,
    PRIMARY KEY (ID_TAREA_RAM, ID_ALIAS, ID_ALIAS_ACOPLE)
);