CREATE TABLE IF NOT EXISTS AJENOS.ALIAS_AJENO (
    ID_ALIAS INTEGER NOT NULL,
    ID_AJENO BIGINT NOT NULL,
    ID_TIPO_ESTADO_AJENO_RAM SMALLINT NOT NULL,
    FECHA_ALTA TIMESTAMP NOT NULL,
    USUARIO_ALTA VARCHAR(140) NOT NULL,
    FECHA_MODIFICACION TIMESTAMP NULL,
    USUARIO_MODIFICACION VARCHAR(140) NULL,
    FECHA_BAJA TIMESTAMP NULL,
    USUARIO_BAJA VARCHAR(140) NULL,
    ID_SINT VARCHAR(140) NULL,
    PRIMARY KEY (ID_ALIAS, ID_AJENO)
);