CREATE TABLE IF NOT EXISTS AJENOS.ALIAS_AMBITO (
    ID_ALIAS_AMBITO INTEGER NOT NULL,
    ID_ALIAS INTEGER NOT NULL,
    ID_GRUPO_CADENA SMALLINT NULL,
    ID_PAIS SMALLINT NULL,
    ID_LOCALIZACION_COMPRA BIGINT NULL,
    FECHA_ALTA TIMESTAMP NOT NULL,
    USUARIO_ALTA VARCHAR(410) NOT NULL,
    FECHA_MODIFICACION TIMESTAMP NULL,
    USUARIO_MODIFICACION VARCHAR(140) NULL,
    FECHA_BAJA TIMESTAMP NULL,
    USUARIO_BAJA VARCHAR(140) NULL,
    ID_TIPO_REGLA_AMBITO SMALLINT NOT NULL,
    ID_CADENA SMALLINT NULL,
    PRIMARY KEY (ID_ALIAS_AMBITO)
);