CREATE TABLE IF NOT EXISTS AJENOS.ALIAS_IDIOMA (
    ID_ALIAS INTEGER NOT NULL,
    ID_IDIOMA SMALLINT NOT NULL,
    DESCRIPCION VARCHAR(1200) NOT NULL,
    NOMBRE VARCHAR(1200) NOT NULL,
    PRIMARY KEY (ID_ALIAS, ID_IDIOMA)
);