CREATE TABLE IF NOT EXISTS AJENOS.ALIAS_TAREA (
    ID_TAREA_RAM BIGINT NOT NULL,
    ID_ALIAS INTEGER NOT NULL,
    FECHA_ALTA TIMESTAMP NOT NULL,
    USUARIO_ALTA VARCHAR(410) NOT NULL,
    FECHA_MODIFICACION TIMESTAMP NULL,
    USUARIO_MODIFICACION VARCHAR(410) NULL,
    FECHA_BAJA TIMESTAMP NULL,
    USUARIO_BAJA VARCHAR(410) NULL,
    ID_TIPO_ALIAS SMALLINT NULL,
    ID_TIPO_CONEXION_ORIGEN_DATO_ALIAS SMALLINT NULL,
    PRIMARY KEY (ID_TAREA_RAM, ID_ALIAS)
);