CREATE TABLE IF NOT EXISTS MAESTROS.CADENA (
    ID_CADENA SMALLINT NOT NULL,
    NOMBRE VARCHAR(400) NOT NULL,
    MARCA_COMERCIAL CHAR(70) NOT NULL,
    LOGO TEXT NULL,
    FECHA_ALTA TIMESTAMP NOT NULL,
    USUARIO_ALTA VARCHAR(200) NOT NULL,
    FECHA_MODIFICACION TIMESTAMP NULL,
    USUARIO_MODIFICACION VARCHAR(200) NULL,
    MARCA_COMERCIAL_AS400 CHAR(20) NULL,
    COD_CADENA_PDA VARCHAR(100) NULL,
    NOMBRE_CORTO VARCHAR(100) NULL,
    PRIMARY KEY (ID_CADENA)
);