CREATE TABLE IF NOT EXISTS AJENOS.EVENTO_RAM (
    ID_EVENTO_RAM BIGINT NOT NULL,
    ID_TIPO_ESTADO_EVENTO_RAM SMALLINT NOT NULL,
    ID_TIPO_EVENTO_RAM SMALLINT NOT NULL,
    NOMBRE VARCHAR(800) NOT NULL,
    DESCRIPCION VARCHAR(2000) NOT NULL,
    FECHA_ALTA TIMESTAMP NOT NULL,
    USUARIO_ALTA VARCHAR(400) NOT NULL,
    FECHA_MODIFICACION TIMESTAMP NULL,
    USUARIO_MODIFICACION VARCHAR(400) NULL,
    FECHA_BAJA TIMESTAMP NULL,
    USUARIO_BAJA VARCHAR(400) NULL,
    ID_TIPO_ESTADO_LINEA_COMPRAS SMALLINT NULL,
    ID_TIPO_TAREA SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID_EVENTO_RAM)
);