CREATE TABLE IF NOT EXISTS MAESTROS.GRUPO_CADENA_CADENA (
    ID_GRUPO_CADENA INTEGER NOT NULL,
    ID_CADENA SMALLINT NOT NULL,
    FECHA_ALTA TIMESTAMP NOT NULL,
    USUARIO_ALTA VARCHAR(200) NOT NULL,
    FECHA_MODIFICACION TIMESTAMP NULL,
    USUARIO_MODIFICACION VARCHAR(200) NULL,
    PRIMARY KEY (ID_GRUPO_CADENA, ID_CADENA)
);