CREATE TABLE IF NOT EXISTS AJENOS.LOCALIZACION_COMPRA_RAM (
    ID_LOCALIZACION_COMPRA_RAM BIGINT NOT NULL,
    ID_LOCALIZACION_COMPRA BIGINT NOT NULL,
    ID_TIPO_ESTADO_LOCALIZACION_RAM SMALLINT NOT NULL,
    FECHA_ALTA TIMESTAMP NOT NULL,
    USUARIO_ALTA VARCHAR(400) NOT NULL,
    FECHA_MODIFICACION TIMESTAMP NULL,
    USUARIO_MODIFICACION VARCHAR(400) NULL,
    FECHA_BAJA TIMESTAMP NULL,
    USUARIO_BAJA VARCHAR(400) NULL,
    ID_GRUPO_CADENA INTEGER NOT NULL,
    PRIMARY KEY (ID_LOCALIZACION_COMPRA_RAM)
);