CREATE TABLE IF NOT EXISTS AJENOS.TAREA_AMBITO_APLANADO (
    ID_TAREA_AMBITO_APLANADO BIGINT NOT NULL,
    ID_TAREA_AMBITO BIGINT NOT NULL,
    ID_LOCALIZACION_COMPRA BIGINT NOT NULL,
    ID_TIPO_ESTADO_LOCALIZACION_RAM SMALLINT NOT NULL,
    ID_TIPO_ESTADO_LOCALIZACION_TAREA SMALLINT NOT NULL,
    ID_ALIAS INTEGER NOT NULL,
    FECHA_ALTA TIMESTAMP NOT NULL,
    USUARIO_ALTA VARCHAR(400) NOT NULL,
    FECHA_MODIFICACION TIMESTAMP NULL,
    USUARIO_MODIFICACION VARCHAR(400) NULL,
    FECHA_BAJA TIMESTAMP NULL,
    USUARIO_BAJA VARCHAR(400) NULL,
    ID_TIPO_ALIAS SMALLINT NULL,
    ID_TIPO_CONEXION_ORIGEN_DATO_ALIAS SMALLINT NULL,
    ID_ALIAS_ACOPLE INTEGER NULL,
    RN INTEGER NULL,
    PRIMARY KEY (ID_TAREA_AMBITO_APLANADO)
);