CREATE TABLE IF NOT EXISTS AJENOS.TAREA_AMBITO (
    ID_TAREA_AMBITO BIGINT NOT NULL,
    ID_TAREA_RAM BIGINT NOT NULL,
    ID_GRUPO_CADENA INTEGER NULL,
    ID_LOCALIZACION_COMPRA BIGINT NULL,
    ID_PAIS SMALLINT NULL,
    ID_TIPO_REGLA_AMBITO SMALLINT NOT NULL,
    FECHA_ALTA TIMESTAMP NOT NULL,
    USUARIO_ALTA VARCHAR(400) NOT NULL,
    FECHA_MODIFICACION TIMESTAMP NULL,
    USUARIO_MODIFICACION VARCHAR(400) NULL,
    FECHA_BAJA TIMESTAMP NULL,
    USUARIO_BAJA VARCHAR(400) NULL,
    ID_CADENA SMALLINT NULL,
    PRIMARY KEY (ID_TAREA_AMBITO)
);