CREATE TABLE IF NOT EXISTS AJENOS.TAREA_RAM (
    ID_TAREA_RAM BIGINT NOT NULL,
    NOMBRE VARCHAR(1200) NOT NULL,
    DESCRIPCION VARCHAR(1200) NOT NULL,
    ID_TIPO_TAREA SMALLINT NOT NULL,
    ID_TIPO_ESTADO_TAREA_RAM SMALLINT NOT NULL,
    FECHA_ALTA TIMESTAMP NOT NULL,
    USUARIO_ALTA VARCHAR(4000) NOT NULL,
    FECHA_MODIFICACION TIMESTAMP NULL,
    USUARIO_MODIFICACION VARCHAR(400) NULL,
    FECHA_BAJA TIMESTAMP NULL,
    USUARIO_BAJA VARCHAR(400) NULL,
    PRIMARY KEY (ID_TAREA_RAM)
);