CREATE TABLE IF NOT EXISTS AJENOS.MAQUINA_ESTADO_AJENOS (
    ID_MAQUINA_ESTADO_AJENOS INTEGER NOT NULL,
    ID_TIPO_MAQUINA_ESTADO SMALLINT NOT NULL,
    ID_TIPO_ESTADO_ACTUAL INTEGER NOT NULL,
    FECHA_HORA_INICIO_VALIDEZ TIMESTAMP NOT NULL,
    FECHA_ALTA TIMESTAMP NOT NULL,
    USUARIO_ALTA VARCHAR(400) NOT NULL,
    PRIMARY KEY (ID_MAQUINA_ESTADO_AJENOS)
);