CREATE TABLE IF NOT EXISTS AJENOS.TIPO_ESTADO_IDIOMA (
    ID_TIPO_ESTADO INTEGER NOT NULL,
    ID_IDIOMA SMALLINT NOT NULL,
    DESCRIPCION VARCHAR(1400) NOT NULL,
    NOMBRE_CORTO VARCHAR(500) NULL,
    PRIMARY KEY (ID_TIPO_ESTADO, ID_IDIOMA)
);