CREATE TABLE IF NOT EXISTS MAESTROS.UNIDADES_MEDIDA_IDIOMA (
    ID_UNIDADES_MEDIDA SMALLINT NOT NULL,
    ID_IDIOMA SMALLINT NOT NULL,
    DESCRIPCION VARCHAR(1400) NULL,
    DESCRIPCION_CORTA VARCHAR(500) NULL,
    PRIMARY KEY (ID_UNIDADES_MEDIDA, ID_IDIOMA)
);