CREATE TABLE IF NOT EXISTS AJENOS.TIPO_ESTADO_LOCALIZACION_RAM_IDIOMA (
    ID_TIPO_ESTADO_LOCALIZACION_RAM SMALLINT NOT NULL,
    ID_IDIOMA SMALLINT NOT NULL,
    DESCRIPCION VARCHAR(1400) NULL,
    PRIMARY KEY (ID_TIPO_ESTADO_LOCALIZACION_RAM, ID_IDIOMA)
);