CREATE TABLE IF NOT EXISTS MAESTROS.TIENDA_HISTORICO (
    ID_TIENDA INTEGER NOT NULL,
    ID_ESTADO_TIENDA SMALLINT NOT NULL,
    FECHA_HORA_DESDE TIMESTAMP NOT NULL,
    FECHA_HORA_HASTA TIMESTAMP NULL,
    ID_SUBESTADO_TIENDA SMALLINT NULL, 
    ESTADO_VIGENTE DECIMAL(1,0) NULL,
    PRIMARY KEY (ID_TIENDA)
);