CREATE TABLE IF NOT EXISTS MAESTROS.ESTADO_TIENDA_IDIOMA (
    ID_ESTADO_TIENDA SMALLINT NOT NULL,
    ID_IDIOMA SMALLINT NOT NULL,
    DESCRIPCION VARCHAR(1000) NOT NULL,
    PRIMARY KEY (ID_ESTADO_TIENDA)
);