CREATE TABLE IF NOT EXISTS AJENOS.GRUPO_LOCALIZACION_COMPRA_LOCALIZACION_COMPRA (
    ID_GRUPO_LOCALIZACION_COMPRA_LOCALIZACION_COMPRA INTEGER NOT NULL,
    ID_GRUPO_LOCALIZACION_COMPRA INTEGER NOT NULL,
    ID_LOCALIZACION_COMPRA BIGINT NOT NULL,
    USUARIO_ALTA VARCHAR(600) NOT NULL,
    FECHA_ALTA TIMESTAMP NOT NULL,
    PRIMARY KEY (ID_GRUPO_LOCALIZACION_COMPRA_LOCALIZACION_COMPRA)
);