CREATE TABLE IF NOT EXISTS AJENOS.GRUPO_LOCALIZACION_COMPRA (
    ID_GRUPO_LOCALIZACION_COMPRA INTEGER NOT NULL,
    DESCRIPCION VARCHAR(600) NOT NULL,
    ID_TIPO_GRUPO_LOCALIZACION_COMPRA SMALLINT NOT NULL,
    PRIORIDAD DECIMAL(4, 0) NOT NULL,
    ID_DEPARTAMENTO_EMPRESA_GRUPO SMALLINT NOT NULL,
    USUARIO_ALTA VARCHAR(500) NOT NULL,
    FECHA_ALTA TIMESTAMP NOT NULL,
    USUARIO_MODIFICACION VARCHAR(500) NULL,
    FECHA_MODIFICACION TIMESTAMP NULL,
    USUARIO_BAJA VARCHAR(500) NULL,
    FECHA_BAJA TIMESTAMP NULL,
    PRIMARY KEY (ID_GRUPO_LOCALIZACION_COMPRA)
);