CREATE TABLE IF NOT EXISTS AJENOS.TIPO_ESTADO_ALIAS (
    ID_TIPO_ESTADO_ALIAS SMALLINT NOT NULL,
    DESCRIPCION VARCHAR(600) NOT NULL,
    FECHA_ALTA TIMESTAMP NOT NULL,
    USUARIO_ALTA VARCHAR(500) NOT NULL,
    FECHA_MODIFICACION TIMESTAMP NULL,
    USUARIO_MODIFICACION VARCHAR(500) NULL,
    FECHA_BAJA TIMESTAMP NULL,
    USUARIO_BAJA VARCHAR(500) NULL,
    PRIMARY KEY (ID_TIPO_ESTADO_ALIAS)
);