CREATE TABLE IF NOT EXISTS AJENOS.TIPO_ESTADO_ALIAS_IDIOMA (
    ID_TIPO_ESTADO_ALIAS SMALLINT NOT NULL,
    ID_IDIOMA SMALLINT NOT NULL,
    DESCRIPCION VARCHAR(600) NOT NULL,
    PRIMARY KEY (ID_TIPO_ESTADO_ALIAS, ID_IDIOMA)
);