CREATE TABLE IF NOT EXISTS AJENOS.TIPO_ESTACIONALIDAD_IDIOMA (
    ID_TIPO_ESTACIONALIDAD SMALLINT NOT NULL,
    ID_IDIOMA SMALLINT NOT NULL,
    DESCRIPCION VARCHAR(600) NOT NULL,
    PRIMARY KEY (ID_TIPO_ESTACIONALIDAD, ID_IDIOMA)
);