CREATE TABLE IF NOT EXISTS AJENOS.TIPO_CONEXION_ORIGEN_DATO_ALIAS (
    ID_TIPO_CONEXION_ORIGEN_DATO_ALIAS SMALLINT NOT NULL,
    DESCRIPCION VARCHAR(600) NOT NULL,
    FECHA_ALTA TIMESTAMP NOT NULL,
    USUARIO_ALTA VARCHAR(50) NOT NULL,
    FECHA_MODIFICACION TIMESTAMP NULL,
    USUARIO_MODIFICACION VARCHAR(50) NULL,
    FECHA_BAJA TIMESTAMP NULL,
    USUARIO_BAJA VARCHAR(50) NULL,
    PRIMARY KEY (ID_TIPO_CONEXION_ORIGEN_DATO_ALIAS)
);