CREATE TABLE IF NOT EXISTS AJENOS.TIPO_CONEXION_ORIGEN_DATO_ALIAS_IDIOMA (
    ID_TIPO_CONEXION_ORIGEN_DATO_ALIAS SMALLINT NOT NULL,
    ID_IDIOMA SMALLINT NOT NULL,
    DESCRIPCION VARCHAR(600) NOT NULL,
    PRIMARY KEY (ID_TIPO_CONEXION_ORIGEN_DATO_ALIAS, ID_IDIOMA)
);