CREATE TABLE IF NOT EXISTS MAESTROS.IDIOMA (
    ID_IDIOMA SMALLINT NOT NULL,
    DESCRIPCION VARCHAR(600) NOT NULL,
    NOMBRE_CORTO CHARACTER(5) NULL,
    COD_IDIOMA_SQL CHARACTER(5) NULL,
    ID_IDIOMA_PADRE SMALLINT NULL,
    FECHA_ALTA TIMESTAMP NOT NULL,
    USUARIO_ALTA VARCHAR(50) NOT NULL,
    FECHA_MODIFICACION TIMESTAMP NULL,
    USUARIO_MODIFICACION VARCHAR(50) NULL,
    PAIS_IDIOMA_ISO CHARACTER(2) NULL,
    IDIOMA_ISO CHARACTER(2) NULL,
    PRIMARY KEY (ID_IDIOMA)
);