CREATE TABLE IF NOT EXISTS AJENOS.TIPO_ESTADO_TAREA_RAM_IDIOMA (
    ID_TIPO_ESTADO_TAREA_RAM SMALLINT NOT NULL,
    ID_IDIOMA SMALLINT NOT NULL,
    DESCRIPCION VARCHAR(600) NOT NULL,
    PRIMARY KEY (ID_TIPO_ESTADO_TAREA_RAM, ID_IDIOMA)
);