CREATE TABLE IF NOT EXISTS AJENOS.TIPO_ESTADO_TAREA_RAM (
    ID_TIPO_ESTADO_TAREA_RAM SMALLINT NOT NULL,
    DESCRIPCION VARCHAR(600) NOT NULL,
    FECHA_ALTA TIMESTAMP NOT NULL,
    USUARIO_ALTA VARCHAR(50) NOT NULL,
    FECHA_MODIFICACION TIMESTAMP NULL,
    USUARIO_MODIFICACION VARCHAR(50) NULL,
    FECHA_BAJA TIMESTAMP NULL,
    USUARIO_BAJA VARCHAR(50) NULL,
    PRIMARY KEY (ID_TIPO_ESTADO_TAREA_RAM)
);