CREATE TABLE IF NOT EXISTS AJENOS.TIPO_TAREA_IDIOMA (
    ID_TIPO_TAREA SMALLINT NOT NULL,
    ID_IDIOMA SMALLINT NOT NULL,
    DESCRIPCION VARCHAR(600) NOT NULL,
    PRIMARY KEY (ID_TIPO_TAREA, ID_IDIOMA)
);