CREATE TABLE IF NOT EXISTS MAESTROS.DEPARTAMENTO_EMPRESA_GRUPO(
    ID_DEPARTAMENTO_EMPRESA_GRUPO SMALLINT NOT NULL,
    ID_DEPARTAMENTO INTEGER NOT NULL,
    ID_EMPRESA_GRUPO INTEGER NOT NULL,
    NOMBRE VARCHAR(500) NOT NULL,
    USUARIO_ALTA VARCHAR(500) NOT NULL,
    FECHA_ALTA VARCHAR(500) NOT NULL,
    USUARIO_MODIFICACION VARCHAR(500) NULL,
    FECHA_MODIFICACION VARCHAR(500) NULL,
    USUARIO_BAJA VARCHAR(50) NULL,
    FECHA_BAJA TIMESTAMP NULL,
    ID_TIPO_DEPARTAMENTO_EMPRESA_GRUPO SMALLINT NULL,
    ID_DEPARTAMENTO_EMPRESA_GRUPO_VALIDADOR SMALLINT NULL,
    PRIMARY KEY (ID_DEPARTAMENTO_EMPRESA_GRUPO)
);
	 