CREATE TABLE IF NOT EXISTS AJENOS.TIPO_ESTADO_LOCALIZACION_TAREA_IDIOMA(
    ID_TIPO_ESTADO_LOCALIZACION_TAREA SMALLINT NOT NULL,
    ID_IDIOMA SMALLINT NOT NULL,
    DESCRIPCION VARCHAR(500) NOT NULL,
    PRIMARY KEY (ID_TIPO_ESTADO_LOCALIZACION_TAREA, ID_IDIOMA)
);