CREATE TABLE IF NOT EXISTS AJENOS.TIPO_REGLA_AMBITO_IDIOMA(
    ID_TIPO_REGLA_AMBITO SMALLINT NOT NULL,
    ID_IDIOMA SMALLINT NOT NULL,
    DESCRIPCION VARCHAR(500) NOT NULL,
    PRIMARY KEY (ID_TIPO_REGLA_AMBITO, ID_IDIOMA)
);