CREATE TABLE IF NOT EXISTS AJENOS.TIPO_ESTADO_EVENTO_RAM_IDIOMA(
    ID_TIPO_ESTADO_EVENTO_RAM SMALLINT NOT NULL,
    ID_IDIOMA SMALLINT NOT NULL,
    DESCRIPCION VARCHAR(500) NOT NULL,
    PRIMARY KEY (ID_TIPO_ESTADO_EVENTO_RAM, ID_IDIOMA)
);