CREATE TABLE IF NOT EXISTS AJENOS.TIPO_ESTADO_LINEA_COMPRAS_IDIOMA(
    ID_TIPO_ESTADO_LINEA_COMPRAS SMALLINT NOT NULL,
    ID_IDIOMA SMALLINT NOT NULL,
    DESCRIPCION VARCHAR(500) NOT NULL,
    PRIMARY KEY (ID_TIPO_ESTADO_LINEA_COMPRAS, ID_IDIOMA)
);