CREATE TABLE IF NOT EXISTS AJENOS.EVENTO_EJECUCION_RAM (
    ID_EVENTO_EJECUCION_RAM BIGINT NOT NULL,
    COD_EJECUCION BIGINT NULL,
    ID_EVENTO_RAM BIGINT NOT NULL,
    ID_TIPO_ESTADO_EVENTO_EJECUCION_RAM SMALLINT NOT NULL,
    FECHA_HORA_INICIO_EJECUCION TIMESTAMP NULL,
    FECHA_HORA_FIN_EJECUCION TIMESTAMP NULL,
    FECHA_ALTA TIMESTAMP NOT NULL,
    USUARIO_ALTA VARCHAR(140) NOT NULL,
    FECHA_MODIFICACION TIMESTAMP NULL,
    USUARIO_MODIFICACION VARCHAR(140) NULL,
    FECHA_BAJA TIMESTAMP NULL,
    USUARIO_BAJA VARCHAR(140) NULL,
    ID_LOCALIZACION_COMPRA BIGINT NULL,
    ID_AJENO BIGINT NOT NULL,
    ID_TIPO_EJECUCION_RAM SMALLINT NOT NULL,
    RN INTEGER NULL,
    PRIMARY KEY (ID_EVENTO_EJECUCION_RAM)
);