version: '3.8'

services:
  node-service:
    build: ./backend/node
    container_name: node-service
    ports:
      - "5000:5000"
    volumes:
      - ./backend/node:/app:ro
    depends_on:
      - mysqldb
    networks:
      - app-network
    restart: always
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database/mysql:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    # Este comando modifica la secuencia de arranque para ejecutar tu script de inicialización
    command: >
      bash -c "
      echo 'Contenedor iniciando...' &&
      chmod +x /docker-entrypoint-initdb.d/init.sh &&
      /usr/local/bin/docker-entrypoint.sh mysqld
      "
    networks:
      - app-network
    restart: always

volumes:
  mysql-data:

networks:
  app-network: