USE AJENOS;

INSERT INTO AJENOS.TIPO_ESTADO_LOCALIZACION_RAM_IDIOMA (ID_TIPO_ESTADO_LOCALIZACION_RAM,ID_IDIOMA,DESCRIPCION) VALUES
	 (1,1,'Active'),
	 (2,1,'Paused'),
	 (1,3,'Activa'),
	 (2,3,'Pausada');
