USE AJENOS;

INSERT INTO AJENOS.TIPO_CONEXION_ORIGEN_DATO_ALIAS (ID_TIPO_CONEXION_ORIGEN_DATO_ALIAS,DESCRIPCION,FECHA_ALTA,USUARIO_ALTA,FECHA_MODIFICACION,USUARIO_MODIFICACION,FECHA_BAJA,USUARIO_BAJA) VALUES
	 (1,'MAIN','2022-12-12 00:00:00.0','MAJENOS',NULL,NULL,NULL,NULL),
	 (2,'COUPLING','2022-12-12 00:00:00.0','MAJENOS',NULL,NULL,NULL,NULL);
