USE AJENOS;

INSERT INTO AJENOS.TIPO_CONEXION_ORIGEN_DATO_ALIAS_IDIOMA (ID_TIPO_CONEXION_ORIGEN_DATO_ALIAS,ID_IDIOMA,DESCRIPCION) VALUES
	 (1,3,'PRINCIPAL'),
	 (2,3,'ACOPLE'),
	 (1,1,'MAIN'),
	 (2,1,'COUPLING');
