USE AJENOS;

INSERT INTO AJENOS.TIPO_ESTADO_TAREA_RAM_IDIOMA (ID_TIPO_ESTADO_TAREA_RAM,ID_IDIOMA,DESCRIPCION) VALUES
	 (1,1,'ACTIVE'),
	 (1,3,'ACTIVA'),
	 (2,1,'PAUSED'),
	 (2,3,'PAUSADA'),
	 (3,3,'ELIMINADA'),
	 (3,1,'DELETED');
