USE AJENOS;

INSERT INTO AJENOS.TIPO_ESTADO_LOCALIZACION_TAREA (ID_TIPO_ESTADO_LOCALIZACION_TAREA,DESCRIPCION,FECHA_ALTA,USUARIO_ALTA,FECHA_MODIFICACION,USUARIO_MODIFICACION,FECHA_BAJA,USUARIO_BAJA) VALUES
	 (1,'ACTIVE','2022-09-27 15:00:00.0','MAJENOS',NULL,NULL,NULL,NULL),
	 (2,'PAUSED','2022-09-27 15:00:00.0','MAJENOS',NULL,NULL,NULL,NULL);
