USE AJENOS;

INSERT INTO AJENOS.TIPO_ESTADO_LOCALIZACION_TAREA_IDIOMA (ID_TIPO_ESTADO_LOCALIZACION_TAREA,ID_IDIOMA,DESCRIPCION) VALUES
	 (1,1,'ACTIVE'),
	 (2,1,'PAUSED'),
	 (1,3,'ACTIVO'),
	 (2,3,'PAUSADO');
