USE AJENOS;

INSERT INTO AJENOS.TIPO_EVENTO_RAM_IDIOMA (ID_TIPO_EVENTO_RAM,ID_IDIOMA,DESCRIPCION) VALUES
	 (3,1,'PUNCTUAL'),
	 (1,3,'RECURRENTE'),
	 (2,3,'MANUAL'),
	 (3,3,'PUNTUAL'),
	 (1,1,'RECURRENT'),
	 (2,1,'MANUAL');
