USE AJENOS;

INSERT INTO AJENOS.TIPO_ESTADO_EVENTO_RAM_IDIOMA (ID_TIPO_ESTADO_EVENTO_RAM,ID_IDIOMA,DESCRIPCION) VALUES
	 (1,3,'PAUSADO'),
	 (2,3,'ACTIVO'),
	 (3,3,'BORRADO'),
	 (1,1,'PAUSED'),
	 (2,1,'ACTIVE'),
	 (3,1,'DELETED'),
	 (4,1,'IN PROGRESS'),
	 (4,3,'EN EJECUCION');
