USE AJENOS;

INSERT INTO AJENOS.TIPO_ESTADO_LINEA_COMPRAS_IDIOMA (ID_TIPO_ESTADO_LINEA_COMPRAS,ID_IDIOMA,DESCRIPCION) VALUES
	 (1,1,'PROPOSED'),
	 (1,3,'PROPUESTA'),
	 (2,3,'INICIADA'),
	 (2,1,'STARTED');
