USE AJENOS;

INSERT INTO AJENOS.TIPO_ESTADO_PROPUESTA_RAM_IDIOMA (ID_TIPO_ESTADO_PROPUESTA_RAM,ID_IDIOMA,DESCRIPCION) VALUES
	 (1,1,'PUBLISHED'),
	 (2,1,'PENDING'),
	 (3,1,'DELETED'),
	 (1,3,'PUBLICADO'),
	 (2,3,'PENDIENTE'),
	 (3,3,'ELIMINADO');
