USE AJENOS;

INSERT INTO AJENOS.TIPO_ESTADO_LINEA_COMPRAS (ID_TIPO_ESTADO_LINEA_COMPRAS,DESCRIPCION,FECHA_ALTA,USUARIO_ALTA,FECHA_MODIFICACION,USUARIO_MODIFICACION,FECHA_BAJA,USUARIO_BAJA) VALUES
	 (1,'PROPOSED','2022-09-26 13:00:00.0','RAM',NULL,NULL,NULL,NULL),
	 (2,'STARTED','2022-09-26 13:00:00.0','RAM',NULL,NULL,NULL,NULL);
