USE AJENOS;
INSERT INTO AJENOS.TIPO_ESTADO_RECUENTO_RAM_IDIOMA (ID_TIPO_ESTADO_RECUENTO_RAM,ID_IDIOMA,DESCRIPCION) VALUES
	 (1,3,'PENDIENTE'),
	 (2,3,'RECOGIDO'),
	 (3,3,'RESPUESTA'),
	 (4,3,'VALIDADO'),
	 (5,3,'DESCARTADO'),
	 (1,1,'PENDING'),
	 (2,1,'RECEIVED'),
	 (3,1,'ANSWERED'),
	 (4,1,'VALIDATED'),
	 (5,1,'DISCARDED');
